<?php
namespace Terrific\ExporterBundle\Tests\Filter {
    use Terrific\ExporterBundle\Helper\FileHelper;

    /**
     * Generated by PHPUnit_SkeletonGenerator on 2012-09-08 at 09:30:13.
     */
    class FileHelperTest extends \PHPUnit_Framework_TestCase {
        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp() {
        }

        /**
         * Tears down the fixture, for example, closes a network connection.
         * This method is called after a test is executed.
         */
        protected function tearDown() {
        }


        /**
         * @covers \Terrific\ExporterBundle\Helper\FileHelper::isJavascript
         */
        public function testIsJavascript() {
            $this->assertTrue(FileHelper::isJavascript('test.js'), "test.js is a javascript file.");
            $this->assertTrue(FileHelper::isJavascript('asdfasdf.JS'), "asdfasdf.JS is a javascript file.");

            $this->assertFalse(FileHelper::isJavascript('asdf'), "asdf is not a javascript file.");
            $this->assertFalse(FileHelper::isJavascript('test-file-js'), "test-file-js is not a javascript file.");
        }

        /**
         * @covers \Terrific\ExporterBundle\Helper\FileHelper::isStylesheet
         */
        public function testIsStylesheet() {
            $this->assertTrue(FileHelper::isStylesheet('test.css'), "test.css should be marked as stylesheet.");
            $this->assertTrue(FileHelper::isStylesheet('asdfasdf.CSS'), "asdfasdf.CSS should be marked as stylesheet.");

            $this->assertFalse(FileHelper::isStylesheet('asdf'), "asdf is not a stylesheet.");
            $this->assertFalse(FileHelper::isStylesheet('test-file-css'), "test-file-css is not a stylessheet.");
        }

    }
}
