<?php
namespace Terrific\ExporterBundle\Tests\Filter {
    use Terrific\ExporterBundle\Helper\NumberHelper;

    /**
     * Generated by PHPUnit_SkeletonGenerator on 2012-09-08 at 09:30:13.
     */
    class NumberHelperTest extends \PHPUnit_Framework_TestCase {
        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp() {
        }

        /**
         * Tears down the fixture, for example, closes a network connection.
         * This method is called after a test is executed.
         */
        protected function tearDown() {
        }


        /**
         * @covers NumberHelper:formatBytes()
         */
        public function testFormatBytes() {
            $this->assertEquals("123 Byte", NumberHelper::formatBytes(123));
            $this->assertEquals("1.00 kByte", NumberHelper::formatBytes(1024));
            $this->assertEquals("1.10 kByte", NumberHelper::formatBytes(1124));
            $this->assertEquals("1.00 MByte", NumberHelper::formatBytes(1048576));
            $this->assertEquals("1.01 MByte", NumberHelper::formatBytes(1058576));
        }
    }
}
