<?php
namespace Terrific\ExporterBundle\Tests\Filter {
    use Terrific\ExporterBundle\Helper\StringHelper;

    /**
     * Generated by PHPUnit_SkeletonGenerator on 2012-09-08 at 09:30:13.
     */
    class StringHelperTest extends \PHPUnit_Framework_TestCase {
        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp() {
        }

        /**
         * Tears down the fixture, for example, closes a network connection.
         * This method is called after a test is executed.
         */
        protected function tearDown() {
        }

        /**
         * @covers StringHelper::escapeFileLabel
         */
        public function testEscapeFileLabel() {
            $this->assertEquals("Content_Image", StringHelper::escapeFileLabel("Content/Image"), "Char / is not correctly replaced.");

            $this->assertEquals("Content_Image", StringHelper::escapeFileLabel("Content#Image"), "Char # were not correctly replaced.");

            $this->assertEquals("Content_Image", StringHelper::escapeFileLabel("Content?Image"), "Char ? were not correctly replaced.");

            $this->assertEquals("Content_Image", StringHelper::escapeFileLabel("Content\\Image"), "Char \\ were not correctly replaced");

            $this->assertEquals("Content_Image", StringHelper::escapeFileLabel("Content&Image"), "Char & were not correctly replaced.");

            $this->assertEquals("Content_Image", StringHelper::escapeFileLabel("Content@Image"), "Char @ were not correctly replaced.");
        }


    }
}
