<?php
namespace Terrific\ExporterBundle\Tests\Service {
    use Terrific\ExporterBundle\Service\ConfigFinder;

    /**
     * Generated by PHPUnit_SkeletonGenerator on 2012-11-11 at 14:56:35.
     */
    class ConfigFinderTest extends \PHPUnit_Framework_TestCase {
        /**
         * @var ConfigFinder
         */
        protected $object;

        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp() {
            $this->object = new ConfigFinder();
            $this->object->setWorkingPath(__DIR__ . "/../Tests/App");
        }

        /**
         * Tears down the fixture, for example, closes a network connection.
         * This method is called after a test is executed.
         */
        protected function tearDown() {
        }


        /**
         * @covers ConfigFinder::find()
         */
        public function testFind() {
            $this->object->find("jshint.json");
        }

    }
}
