<?php
namespace Terrific\ExporterBundle\Tests\Service {
    use Terrific\ExporterBundle\Service\W3CValidator;
    use Terrific\ExporterBundle\Object\ValidationResult;

    /**
     * Generated by PHPUnit_SkeletonGenerator on 2012-11-11 at 14:56:35.
     */
    class W3CValidatorTest extends \PHPUnit_Framework_TestCase {
        /**
         * @var W3CValidator
         */
        protected $object;

        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp() {
            $this->object = new W3CValidator();
        }

        /**
         * Tears down the fixture, for example, closes a network connection.
         * This method is called after a test is executed.
         */
        protected function tearDown() {
        }


        /**
         * @covers W3CValidator::validate()
         */
        public function testValidate() {
            $sampleContent = "<html><head></head><body>Test HTML FILE for w3cValidator</body></html>";

            $ret = $this->object->validate($sampleContent);
            $this->assertTrue(($ret instanceof ValidationResult), "Return value is not a valid ValidationResult class.");


            $sampleContent = "<htt></htt>";
            $ret = $this->object->validate($sampleContent);
            $this->assertTrue(($ret instanceof ValidationResult), "Return value is not a valid ValidationResult class.");

            $this->assertTrue($ret->hasErrors(), "This test should produce errors.");
            $this->assertTrue($ret->hasWarning(), "This test should produce warnings.");
        }

    }
}
