<?php
namespace Terrific\ExporterBundle\Tests\Filter;
use Terrific\ExporterBundle\Filter\ExportPathHTMLFilter;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-08 at 09:30:13.
 */
class ExportPathHTMLFilterTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ExportPathHTMLFilter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ExportPathHTMLFilter(__DIR__ . "/../App");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Terrific\ExporterBundle\Filter\ExportPathHTMLFilter::filterJS
     * @todo   Implement testFilterJS().
     */
    public function testFilterJS()
    {
        $test = '<script type="text/javascript" src="/js/jquerytest.js"></script>';
        $ret = $this->object->filterJS($test);
        $this->assertSame($ret, '<script type="text/javascript" src="../js/jquerytest.js"></script>');

        $test = "<script type='text/javascript' src='/js/jquerytest.js'></script>";
        $ret = $this->object->filterJS($test);
        $this->assertSame($ret, "<script type='text/javascript' src='../js/jquerytest.js'></script>");
    }

    /**
     * @covers Terrific\ExporterBundle\Filter\ExportPathHTMLFilter::filterCSS
     * @todo   Implement testFilterCSS().
     */
    public function testFilterCSS()
    {
        $test ="<link rel='stylesheet' href='/css/compiled/base.css' />";
        $ret = $this->object->filterCSS($test);
        $this->assertSame($ret, "<link rel='stylesheet' href='../css/base.css' />");

        $test ='<link href="/css/compiled/base.css" />';
        $ret = $this->object->filterCSS($test);
        $this->assertSame($ret, '<link href="../css/base.css" />');


    }

    /**
     * @covers Terrific\ExporterBundle\Filter\ExportPathHTMLFilter::filterDATA
     * @todo   Implement testFilterDATA().
     */
    public function testFilterDATA()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Terrific\ExporterBundle\Filter\ExportPathHTMLFilter::filterHTML
     * @todo   Implement testFilterHTML().
     */
    public function testFilterHTML()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        return;
        
        $test = '<img src="/bundles/terrificmoduletest/img/blubb.jpg" />';
        $ret = $this->object->filterHTML($test);
        $this->assertSame($ret, '<img src="../img/Test/blubb.jpg" />');

    }

    /**
     * @covers Terrific\ExporterBundle\Filter\ExportPathHTMLFilter::filter
     * @todo   Implement testFilter().
     */
    public function testFilter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
